imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true

  drsoft_fr.module.product_wizard.ui.front.validation.cart_validator:
    class: DrSoftFr\Module\ProductWizard\UI\Front\Validation\CartValidator
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext().getTranslator()'
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'

  drsoft_fr.module.product_wizard.infrastructure.cart.discount_applier:
    class: DrSoftFr\Module\ProductWizard\Infrastructure\Cart\DiscountApplier
    arguments:
      - '@DrSoftFr\Module\ProductWizard\Domain\Repository\ConfiguratorRepositoryInterface'
      - '@=service("prestashop.adapter.legacy.context").getContext()'

  drsoft_fr.module.product_wizard.infrastructure.cart.cart_creator:
    class: DrSoftFr\Module\ProductWizard\Infrastructure\Cart\CartCreator
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@drsoft_fr.module.product_wizard.infrastructure.cart.discount_applier'
      - '@=service("prestashop.adapter.legacy.context").getContext().getTranslator()'

  DrSoftFr\Module\ProductWizard\Domain\Service\CartCreatorInterface:
    alias: drsoft_fr.module.product_wizard.infrastructure.cart.cart_creator

  drsoft_fr.module.product_wizard.application.command_handler.create_cart_command_handler:
    class: DrSoftFr\Module\ProductWizard\Application\CommandHandler\CreateCartCommandHandler
    autowire: true
    autoconfigure: true
