imports:
  - { resource: ../common.yml }

services:
  drsoft_fr.module.product_wizard.module:
    class: drsoftfrproductwizard
    public: true

  drsoft_fr.module.product_wizard.install.factory.installer_factory:
    class: DrSoftFr\Module\ProductWizard\Install\Factory\InstallerFactory

  drsoft_fr.module.product_wizard.install.installer:
    class: DrSoftFr\Module\ProductWizard\Install\Installer
    factory: 'drsoft_fr.module.product_wizard.install.factory.installer_factory:create'
    public: true
