imports:
  - { resource: ../common.yml }

services:
  DrSoftFr\Module\ProductWizard\UI\Admin\Controller\ConfiguratorController:
    tags: [ 'controller.service_arguments' ]
    arguments:
      - '@drsoft_fr.module.product_wizard.module'

  DrSoftFr\Module\ProductWizard\UI\Admin\Controller\ConfiguratorApiController:
    tags: [ 'controller.service_arguments' ]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'

  DrSoftFr\Module\ProductWizard\Application\Factory\ConfiguratorFactory:
    class: DrSoftFr\Module\ProductWizard\Application\Factory\ConfiguratorFactory
    autowire: true

  drsoft_fr.module.product_wizard.module:
    class: drsoftfrproductwizard
    public: true

  drsoft_fr.module.product_wizard.install.factory.installer_factory:
    class: DrSoftFr\Module\ProductWizard\Install\Factory\InstallerFactory

  drsoft_fr.module.product_wizard.install.installer:
    class: DrSoftFr\Module\ProductWizard\Install\Installer
    factory: 'drsoft_fr.module.product_wizard.install.factory.installer_factory:create'
    public: true
