services:
  # Grid services
  drsoft_fr.module.product_wizard.ui.admin.grid.definition.factory.configurator_grid_definition_factory:
    class: DrSoftFr\Module\ProductWizard\UI\Admin\Grid\Definition\Factory\ConfiguratorGridDefinitionFactory
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  drsoft_fr.module.product_wizard.infrastructure.grid.query_builder.configurator_query_builder:
    class: DrSoftFr\Module\ProductWizard\Infrastructure\Grid\QueryBuilder\ConfiguratorQueryBuilder
    parent: 'prestashop.core.grid.abstract_query_builder'
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'

  drsoft_fr.module.product_wizard.grid.data.factory.configurator_grid_data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@drsoft_fr.module.product_wizard.infrastructure.grid.query_builder.configurator_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'drsoft_fr_product_wizard_configurator'

  drsoft_fr.module.product_wizard.grid.configurator_factory:
    class: PrestaShop\PrestaShop\Core\Grid\GridFactory
    arguments:
      - '@drsoft_fr.module.product_wizard.ui.admin.grid.definition.factory.configurator_grid_definition_factory'
      - '@drsoft_fr.module.product_wizard.grid.data.factory.configurator_grid_data_factory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
    public: true
