services:
  _defaults:
    public: true

  drsoft_fr.module.product_wizard.infrastructure.security.html_sanitizer:
    class: DrSoftFr\Module\ProductWizard\Infrastructure\Security\HtmlSanitizer

  DrSoftFr\Module\ProductWizard\Application\Port\Security\HtmlSanitizerInterface:
    alias: drsoft_fr.module.product_wizard.infrastructure.security.html_sanitizer

  DrSoftFr\Module\ProductWizard\UI\Admin\Normalizer\ConfiguratorNormalizer:
    class: DrSoftFr\Module\ProductWizard\UI\Admin\Normalizer\ConfiguratorNormalizer
    arguments:
      - '@DrSoftFr\Module\ProductWizard\Application\Port\Security\HtmlSanitizerInterface'

  # repository
  drsoft_fr.module.product_wizard.infrastructure.persistence.doctrine.configurator_repository:
    class: DrSoftFr\Module\ProductWizard\Infrastructure\Persistence\Doctrine\ConfiguratorRepository
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - DrSoftFr\Module\ProductWizard\Entity\Configurator

  DrSoftFr\Module\ProductWizard\Domain\Repository\ConfiguratorRepositoryInterface:
    alias: drsoft_fr.module.product_wizard.infrastructure.persistence.doctrine.configurator_repository

  drsoft_fr.module.product_wizard.infrastructure.persistence.doctrine.step_repository:
    class: DrSoftFr\Module\ProductWizard\Infrastructure\Persistence\Doctrine\StepRepository
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - DrSoftFr\Module\ProductWizard\Entity\Step

  drsoft_fr.module.product_wizard.infrastructure.persistence.doctrine.product_choice_repository:
    class: DrSoftFr\Module\ProductWizard\Infrastructure\Persistence\Doctrine\ProductChoiceRepository
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - DrSoftFr\Module\ProductWizard\Entity\ProductChoice

  drsoft_fr.module.product_wizard.service.configurator_presenter:
    class: DrSoftFr\Module\ProductWizard\UI\Hook\Presenter\ConfiguratorPresenter
    arguments:
      - '@drsoft_fr.module.product_wizard.infrastructure.persistence.doctrine.configurator_repository'
