imports:
  - { resource: ./common.yml }

services:
  DrSoftFr\Module\ProductWizard\Controller\Admin\ConfiguratorController:
    tags: [ 'controller.service_arguments' ]

  DrSoftFr\Module\ProductWizard\Form\ConfiguratorType:
    tags:
      - { name: form.type }
    parent: 'form.type.translatable.aware'

  DrSoftFr\Module\ProductWizard\Form\StepType:
    tags:
      - { name: form.type }
    parent: 'form.type.translatable.aware'

  DrSoftFr\Module\ProductWizard\Form\ProductChoiceType:
    tags:
      - { name: form.type }
    parent: 'form.type.translatable.aware'
