imports:
  - { resource: ./common.yml }

services:
  DrSoftFr\Module\ProductWizard\Controller\Admin\ConfiguratorController:
    tags: [ 'controller.service_arguments' ]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'

  DrSoftFr\Module\ProductWizard\Form\ConfiguratorType:
    tags:
      - { name: form.type }
    parent: 'form.type.translatable.aware'

  DrSoftFr\Module\ProductWizard\Form\StepType:
    tags:
      - { name: form.type }
    parent: 'form.type.translatable.aware'

  DrSoftFr\Module\ProductWizard\Form\ProductChoiceType:
    tags:
      - { name: form.type }
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'

  DrSoftFr\Module\ProductWizard\Form\ConditionType:
    tags:
      - { name: form.type }
