admin_drsoft_fr_product_wizard_configurator_index:
  path: /
  methods: [ GET ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\UI\Admin\Controller\ConfiguratorController::indexAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link:
      - AdminDrSoftFrProductWizardConfigurator
      - AdminDrSoftFrProductWizardConfigurator:index

admin_drsoft_fr_product_wizard_configurator_new:
  path: /new
  methods: [ GET, POST ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\UI\Admin\Controller\ConfiguratorController::newAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link: AdminDrSoftFrProductWizardConfigurator:new

admin_drsoft_fr_product_wizard_configurator_edit:
  path: /{id}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\UI\Admin\Controller\ConfiguratorController::editAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link: AdminDrSoftFrProductWizardConfigurator:edit
    _legacy_parameters:
      id: id
  requirements:
    id: \d+

admin_drsoft_fr_product_wizard_configurator_delete:
  path: /{id}/delete
  methods: [ DELETE ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\UI\Admin\Controller\ConfiguratorController::deleteAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link: AdminDrSoftFrProductWizardConfigurator:delete
    _legacy_parameters:
      id: id
  requirements:
    id: \d+

admin_drsoft_fr_product_wizard_configurator_search:
  path: /
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle:Admin\Common:searchGrid
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    gridDefinitionFactoryServiceId: drsoft_fr.module.product_wizard.ui.admin.grid.definition.factory.configurator_grid_definition_factory
    redirectRoute: admin_drsoft_fr_product_wizard_configurator_index
