admin_drsoft_fr_product_wizard_configurator_index:
  path: /
  methods: [ GET ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\Controller\Admin\ConfiguratorController::indexAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link:
      - AdminDrSoftFrProductWizardConfigurator
      - AdminDrSoftFrProductWizardConfigurator:index

admin_drsoft_fr_product_wizard_configurator_new:
  path: /new
  methods: [ GET, POST ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\Controller\Admin\ConfiguratorController::newAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link: AdminDrSoftFrProductWizardConfigurator:new

admin_drsoft_fr_product_wizard_configurator_edit:
  path: /{id}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\Controller\Admin\ConfiguratorController::editAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link: AdminDrSoftFrProductWizardConfigurator:edit
    _legacy_parameters:
      id: id
  requirements:
    id: \d+

admin_drsoft_fr_product_wizard_configurator_delete:
  path: /{id}/delete
  methods: [ GET, POST ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\Controller\Admin\ConfiguratorController::deleteAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link: AdminDrSoftFrProductWizardConfigurator:delete
    _legacy_parameters:
      id: id
  requirements:
    id: \d+

admin_drsoft_fr_product_wizard_configurator_step_fragment:
  path: /step/fragment/
  methods: [ GET ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\Controller\Admin\ConfiguratorController::stepFragmentAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link: AdminDrSoftFrProductWizardConfigurator:stepFragment

admin_drsoft_fr_product_wizard_configurator_product_choice_fragment:
  path: /product-choice/fragment/
  methods: [ GET ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\Controller\Admin\ConfiguratorController::productChoiceFragmentAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link: AdminDrSoftFrProductWizardConfigurator:productChoiceFragment
    _legacy_parameters:
      index: index
  requirements:
    index: \d+

admin_drsoft_fr_product_wizard_configurator_product_search:
  path: /product-search/
  methods: [ GET ]
  defaults:
    _controller: DrSoftFr\Module\ProductWizard\Controller\Admin\ConfiguratorController::productSearchAction
    _legacy_controller: AdminDrSoftFrProductWizardConfigurator
    _legacy_link: AdminDrSoftFrProductWizardConfigurator:productSearch
